name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    steps:
    # Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurer les variables d'environnement
    - name: Set repository variables
      run: |
        echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    # Se connecter à GitHub Packages
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Installer Trivy
    - name: Install Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.28.0/trivy_0.28.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin

    # Construire l'image Docker
    - name: Build Docker image
      run: |
        TAG=$(date +%Y%m%d)-${{ github.sha }}
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest \
                     -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:$TAG .

    # Scanner l'image Docker pour détecter des vulnérabilités
    - name: Reset Trivy database
      run: |
        trivy image --reset

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        update-db: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    # Pousser l'image Docker sur GitHub Packages
    - name: Push Docker image
      run: |
        TAG=$(date +%Y%m%d)-${{ github.sha }}
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:$TAG

